name: Carrier UI Direct Dev CD

variables:
  tags: |
    latest
    $(Build.BuildId)-dev

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev_Deploy
    displayName: Dev Deploy
    jobs:
      - job: Dev_Deploy
        variables:
          - template: /pipelines/templates/variables-dev.yaml
        steps:
          - template: /pipelines/templates/ui/build_push_and_deploy.yaml
            parameters:
              ENVIRONMENT: "dev"
              S3_BUCKET_NAME: "wfai-app-dev"
              CLOUDFRONT_DISTRIBUTION_ID: "E1Q2YIPEZHLHGY"
              PROJECT_ABBREVIATION: "carrier"
              PROJECT_NAME: "carrier-workflow"
