name: Transformer UI PR Check

trigger: none
pr:
  branches:
    # run on PRs from any branch
    include:
      - '*'
  paths:
    include:
      - src/angular-app/**
    exclude:
      - src/Transflo.Platform.Transformer/**
      - infrastructure/**

stages:
  - stage: Check
    jobs:
      - job: Check
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: /pipelines/templates/ui/check.yaml
            parameters:
              PROJECT_ABBREVIATION: "carrier"
              PROJECT_NAME: "carrier-workflow"
